version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers: &reviewers
      - "01bkgift"
    assignees: &assignees
      - "01bkgift"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers: *reviewers
    assignees: *assignees
